#!/bin/bash

SDCARD="/dev/disk/by-id/$ID_BUS-$ID_SERIAL"
FLASH=`cat /tmp/sdburner-src.devname`
AFTER='mplayer /home/pi/1.mp3'
LOGFILE='/var/log/sdflasher.log'
FLASH_CHKSUM_FILE='/tmp/sdburner-src.md5'

if [[ -z $1 ]]; then
    exit 0
fi

if [[ ! -b $SDCARD ]]; then
    exit 0
fi

SDFLASHERD='/home/pi/sdcard_burner/imgburner'
SDFLASHERD_RUN='/var/lock/sdflasherd.lock'

function already_started {
    echo 'Script already started.' 1>&2
    exit 1
}

(
    flock -x -w 1 200 || already_started

    $SDFLASHERD $SDCARD $FLASH $FLASH_CHKSUM_FILE

    if [[ $? == 0 ]]; then
        $AFTER
    fi
) >>$LOGFILE 2>&1 200>$SDFLASHERD_RUN

